### ISSUE TITLE
Allow checking assertions in ClaferIG

### ISSUE THREAD

**Issue by ross2jd** [gsdlab/ClaferChocoIG#14]
Currently, the only way to check assertions is using the "-v" option in the clafer compiler. There should be support to allow the checking of assertions using ClaferChocoIG.

**Comment by mantkiew** [comment]
This has two components: 

1) a command line option `-v` which is analogous to clafer's option `-v`
2) an interactive mode command `validate`, which works the same as for [claferIG #30](https://github.com/gsdlab/claferIG/issues/30).

**Comment by mantkiew** [comment]
Implemented in chocosolver [commit](https://github.com/gsdlab/chocosolver/commit/c14c60a3126454978f6956f855b48833d3b7e28c), see [Validate.java](https://github.com/gsdlab/chocosolver/blob/master/src/main/java/org/clafer/cli/Validate.java).
