### ISSUE TITLE
--prettify option currently only works if used together with --repl

### ISSUE THREAD

**Issue by toeklk** [gsdlab/ClaferChocoIG#8]
Currently, the --prettify option is only working in REPL mode.  The following patch seems to remedy that situation
```
[kgad@lt00583 ~/git/gsdlab/ClaferChocoIG]$  
 git diff
diff --git a/src/main/java/Normal.java b/src/main/java/Normal.java
index 07b1901..3befb68 100644
--- a/src/main/java/Normal.java
+++ b/src/main/java/Normal.java
@@ -77,6 +77,7 @@ public class Normal {
                n = -1;
         
        int index = 0; // instance id
+       boolean prettify = options.has("prettify");
         while (solver.find()) 
        {
                if (n >= 0 && index == n)
@@ -84,9 +85,16 @@ public class Normal {
                
                outStream.println("=== Instance " + (++index) + " Begin ===\n");                    
             InstanceModel instance = solver.instance();
-            for (InstanceClafer c : instance.getTopClafers())
+            if (prettify)
             {
-               Utils.printClafer(c, outStream);
+                instance.print(outStream);
+            }
+            else
+            {
+                for (InstanceClafer c : instance.getTopClafers())
+                {
+                      Utils.printClafer(c, outStream);
+                }
             }
             outStream.println("--- Instance " + (index) + " End ---\n");                    
        }
```

**Comment by mantkiew** [comment]
Yes, we noticed some problems with display since the latest changes on the ChocoSolver side. I have given you write access to this repo, so please feel free to commit this. We are always committing to the `develop` branch and then at some point create a pull request from `develop` to `master` for a release. I only commit directly to master when a `hot fix` is needed. Hmmm, maybe this one is a hot fix, actually.

**Comment by toeklk** [comment]
I think I succeeded.  First of all, I'm a git nitwit, so I hope I didn't screw up.  Basically, I applied the patch to my local develop branch, and then performed a `git push origin develop:develop`.  At least, it _looks as_ if it worked :-/

As far as I can see, there are no real tests with this project, and there are no real coding guidelines used/enforced ATM?
Also, I somewhat "copied" the format of a commit statement of yours, hope that's ok too :-)

**Comment by mantkiew** [comment]
Yes, it worked. Usually, I simply write `git push` and that's it. Git, be default will push to the matching branch, that is, `master` to `origin:master` and `develop` to `origin:develop`. I highly recommend GitHub's own GUI tool [GitHub for Mac](https://mac.github.com/) (I personally use GitHub for Windows). This tool is super convenient for everyday tasks and only occasionally I have to drop to the terminal for more advanced commands.

**Comment by mantkiew** [comment]
Re: coding guidelines. No. 

Actually, longer term I see two paths for this project:

1. Integrate it inside the [chocosolver](https://github.com/gsdlab/chocosolver/) project, which is the actual backend.
2. Remove it completely, and add the functionality to the ClaferIG tool - it would then be able to call both Alloy and Choco given an option. 

Personally, I feel 2. is the way to go but also more work... So for the time being we have to live with ClaferChocoIG, which is an overkill to have it as a separate project.
